### ISSUE TITLE
Please provide the model

### ISSUE THREAD

**Issue by CharlesGong12** [OPTML-Group/Diffusion-MU-Attack#1]
Hi, it seems that you did not provide models from ESD and FMN because the link you placed is still a code repository rather than a model. Thx.

**Comment by jinghanjia** [comment]
Thank you for bringing this to our attention! We have updated the original repository link to include the pre-trained, unlearned weights for both the ESD and FMN models. Please check the link again to access these models. If you encounter any difficulties or cannot find what you're looking for, don't hesitate to reach out for further assistance.
