### ISSUE TITLE
How do you test SPM.

### ISSUE THREAD

**Issue by 120L020904** [OPTML-Group/Diffusion-MU-Attack#10]
SPM uses Lora, do you save it as a Unet in pt format?

**Comment by damon-demon** [comment]
Yes. The tested model checkpoints can be found in [Google Drive](https://drive.google.com/drive/folders/1Nf-EJ2W3CsZwpc5blZFi7tm7o1wEiTg4?usp=sharing). 

More details about how to download them through one command can be found in [AdvUnlearn's Github](https://github.com/OPTML-Group/AdvUnlearn).
