### ISSUE TITLE
Confusion about testing metrics

### ISSUE THREAD

**Issue by 120L020904** [OPTML-Group/Diffusion-MU-Attack#11]
In AdvUnlearn, you mentioned ASR, and the test results are the same as the post-ASR on the project homepage. Is the ASR in AdvUnlearn the same as post-ASR?

**Comment by 120L020904** [comment]
So is the ASR in the table of the paper "DEFENSIVE UNLEARNING WITH ADVERSARIAL TRAINING FOR ROBUST CONCEPT ERASURE IN DIFFUSION MODELS" actually the post-ASR in the paper "To Generate or Not? Safety-Driven Unlearned Diffusion Models Are Still Easy to Generate Unsafe Images ... For Now"?

**Comment by damon-demon** [comment]
The ASR in the table of the paper "AdvUnlearn" is exactly same as its definition in the paper of "UnlearnDiffAtk".
 - ASR = pre-ASR + post-ASR
 
 Pre-ASR denotes the attack sucess rate of original prompt  without any attacks.

**Comment by damon-demon** [comment]
I see. I will correct this. The Post-ASR should be ASR.

**Comment by damon-demon** [comment]
No. It cannot be larger than 100%
