### ISSUE TITLE
Issue when typechecking argument psyh `task.target_ckpt`

### ISSUE THREAD

**Issue by Young1993** [OPTML-Group/Diffusion-MU-Attack#13]
Thank you for open-sourcing such meaningful work.

When I run the cmd:
`python src/execs/attack.py --config-file configs/nudity/text_grad_esd_nudity_classifier.json --attacker.attack_idx 0 --logger.name attack_idx_0`

Argument validation errors
│ Param            │ Issue            │ Got                                                      │
│ task.target_ckpt │ a path to a file │ files/pretrained/SD-1-4/ESD_ckpt/Nudity-ESDx1-UNET-SD.pt │

Do I need to download the  [unlearned model file](https://drive.google.com/file/d/11FNKE_zzm8NMvUQn2_UPWzZRQFd4Frgb/view?usp=sharing)?

**Comment by damon-demon** [comment]
No, that’s not the case. However, you need to set `--task.target_ckpt` to the path of any existing checkpoint file to be evaluated. This checkpoint can correspond to either the text encoder or the UNet of the diffusion model.
