### ISSUE TITLE
Confusion about filter_dataset function

### ISSUE THREAD

**Issue by TtuHamg** [OPTML-Group/Diffusion-MU-Attack#14]
Hi, when I run the `src/execs/attack.py` file, it creates an `ignore.json` file and filters out prompts longer than 60, which causes the dataset to be less than 142. I wonder if these filtered prompts will be considered for attacks.

Looking forward to your reply. 
<img width="482" alt="image" src="https://github.com/user-attachments/assets/674a5c59-1001-4125-9e55-82239f7bdc9c">

**Comment by damon-demon** [comment]
Hi, you may delete the ignore.json file according to your specific requirements. In our initial configuration, we designed the system to reserve space for adversarial prompts varying in length and insertion points. Any prompts that are filtered out will be considered unsuccessful attacks.
