### ISSUE TITLE
style classifier checkpoint

### ISSUE THREAD

**Issue by ajevnisek** [OPTML-Group/Diffusion-MU-Attack#15]
Hi,
Thank you very much for a very comprehensive repo.
I'd love to get the checkpoint for the style eval classifier (in the repo it says that its supposed to be under results/checkpoint-2800)
Thanks!

**Comment by damon-demon** [comment]
Hi,
You can download the style classifier from google drive (https://drive.google.com/file/d/1me_MOrXip1Xa-XaUrPZZY7i49pgFe1po/view?usp=share_link). Feel free to check it.
