### ISSUE TITLE
About multiple-gpus

### ISSUE THREAD

**Issue by CharlesGong12** [OPTML-Group/Diffusion-MU-Attack#2]
Hi, do you remember me. Sorry to bother you again. I am a beginner of stable diffusion model and have some problems when running your code. Did you use a single gpu? I encountered CUDA out of memory with a single 3090-24GB and I could not fit the code into 2 or more gpus due to a lack of multiple-gpus' experience. Thank you very much for answering my rookie questions both this and last time.

**Comment by jinghanjia** [comment]
No worries, our experiments were primarily conducted on a single NVIDIA V100 32 GB GPU.   At the same time, we are actively working on adapting our codebase to support multi-GPU environments.
