### ISSUE TITLE
Threshold for obtaining nudity.csv

### ISSUE THREAD

**Issue by CharlesGong12** [OPTML-Group/Diffusion-MU-Attack#5]
Hello, Author!
Sorry for reaching out again. I wanted to inquire about the threshold you mentioned [here](https://github.com/OPTML-Group/Diffusion-MU-Attack/issues/3) for obtaining the "nudity.csv". Thank you so much for your assistance!

**Comment by damon-demon** [comment]
Hi. The threshold for NudeNet score is 0.75
