### ISSUE TITLE
Could you provide unlearned models for objects?

### ISSUE THREAD

**Issue by TianyunYoung** [OPTML-Group/Diffusion-MU-Attack#6]
Hi~ The work is awesome! I am trying to reproduce the results. I notice that the provided models in the google drive link does not include unlearned models for objects such as church, parachute, tench, and garbage truck. Could you please provide these models? Thank you very much.

**Comment by damon-demon** [comment]
Hello! 

Thank you very much for expressing interest in our project! We appreciate your enthusiasm. For your convenience, the object-unlearned checkpoints are accessible via the following Google Drive link: https://drive.google.com/file/d/11FNKE_zzm8NMvUQn2_UPWzZRQFd4Frgb/view?usp=sharing.

Wishing you a wonderful day! ☀️

**Comment by TianyunYoung** [comment]
Thank you very much
