### ISSUE TITLE
How is the target image obtained?

### ISSUE THREAD

**Issue by AntigoneRandy** [OPTML-Group/Diffusion-MU-Attack#8]
Hi, dear authors, thanks so much for the great work, which is really interesting and inspiring. From Eq.(4) of the paper, it seems that the optimization problem $\max_{c^\prime}p_{\theta^*}(c^\prime|x_\text{tgt})$ requires access to a target image $x_\text{tgt}$. But during evaluation it seems that only the unlearned model parameters and an original prompt are available. Could you please kindly provide details on how is the target image obtained? Thank you very much!

**Comment by damon-demon** [comment]
Hi Boheng,

Thank you for your interest in our work on evaluating unlearned diffusion models. To maintain consistency in our evaluation results, the target images are generated using the original base diffusion model (e.g., SD v1.4). It's important to note that the target images can also be random internet images, provided they are relevant to the concept targeted for erasure.
